from flask import Flask, request, jsonify
from flask_cors import CORS
import requests

app = Flask(__name__)
# Enable CORS so the local frontend can communicate with this backend
CORS(app)

OLLAMA_API_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3"

@app.route('/analyze', methods=['POST'])
def analyze():
    # 1. Get the payload
    data = request.json
    text = data.get('text', '')
    
    if not text:
        return jsonify({'error': 'No text provided'}), 400
        
    # 2. Construct the Prompt exactly as requested
    prompt = f"""Analyze the following internship poster and determine if it is Fake or Real.
Check for red flags such as unrealistic salary, payment requests, missing company details, urgent hiring language, suspicious keywords, and grammar mistakes.
Return the result with reasons and suspicious phrases.

Internship Poster Text:
{text}
"""

    # 3. Payload for Ollama
    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "stream": False
    }
    
    # 4. Make the request to local Ollama instance
    try:
        response = requests.post(OLLAMA_API_URL, json=payload)
        response.raise_for_status()
        result = response.json()
        
        # 5. Return the text response generated by Llama 3
        return jsonify({'response': result.get('response', '')})
        
    except requests.exceptions.ConnectionError:
        return jsonify({'error': 'Failed to connect to Ollama. Make sure Ollama is installed and running at http://localhost:11434.'}), 503
    except Exception as e:
        return jsonify({'error': str(e)}), 500

if __name__ == '__main__':
    print("Starting Fake Internship Detector Backend on port 5000...")
    app.run(debug=True, port=5000)
